name: Link Artifacts
on:
  workflow_run:
    workflows: [App]
    types: [completed]

jobs:
  artifacts-url-comments:
    name: Add links to artifacts in the given jobs
    runs-on: ubuntu-latest
    steps:
      - name: Post artifacts links
        uses: tonyhallett/artifacts-url-comments@v1.1.0
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
            prefix: "Here the packed extension for this build:"
            format: name
            addTo: pull